sign-up / login endpoints

diff --git a/.github/workflows/node.cd.js.yml b/.github/workflows/node.cd.js.yml
--- a/.github/workflows/node.cd.js.yml
+++ b/.github/workflows/node.cd.js.yml
@@ -19,41 +19,41 @@ jobs:
       - name: Create Docker network
         run: sudo docker network create nestjs-network || true
 
-      - name: Create Docker volume
-        run: sudo docker volume create postgres_data || true
-      - name: Stop & Remove existing Postgres container (if running)
-        run: sudo docker rm -f postgres || true
+      # - name: Create Docker volume
+      #   run: sudo docker volume create postgres_data || true
+      # - name: Stop & Remove existing Postgres container (if running)
+      #   run: sudo docker rm -f postgres || true
 
-      - name: Start Postgres container
-        run: |
-          sudo docker run -d \
-            --name postgres \
-            --health-cmd="pg_isready -U ${{secrets.DATABASE_USERNAME}}" \
-            --health-interval=10s \
-            --health-timeout=5s \
-            --health-retries=5 \
-            -e POSTGRES_USER=${{ secrets.DATABASE_USERNAME }} \
-            -e POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
-            -e POSTGRES_DB=${{ secrets.DATABASE_NAME }} \
-            -p 5432:5432 \
-            --network nestjs-network \
-            -v postgres_data:/var/lib/postgresql/data \
-            postgres:15
+      # - name: Start Postgres container
+      #   run: |
+      #     sudo docker run -d \
+      #       --name postgres \
+      #       --health-cmd="pg_isready -U ${{secrets.DATABASE_USERNAME}}" \
+      #       --health-interval=10s \
+      #       --health-timeout=5s \
+      #       --health-retries=5 \
+      #       -e POSTGRES_USER=${{ secrets.DATABASE_USERNAME }} \
+      #       -e POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
+      #       -e POSTGRES_DB=${{ secrets.DATABASE_NAME }} \
+      #       -p 5432:5432 \
+      #       --network nestjs-network \
+      #       -v postgres_data:/var/lib/postgresql/data \
+      #       postgres:15
 
-      - name: Wait for Postgres to be healthy
-        run: |
-          for i in {1..15}; do
-            health=$(sudo docker inspect --format='{{.State.Health.Status}}' postgres)
-              if [ "$health" = "healthy" ]; then
-                echo "Postgres is healthy!"
-                exit 0
-              fi
-              echo "Waiting for Postgres to be healthy..."
-              sleep 5
-            done
-            echo "Postgres did not become healthy in time." >&2
-            docker logs postgres
-            exit 1
+      # - name: Wait for Postgres to be healthy
+      #   run: |
+      #     for i in {1..15}; do
+      #       health=$(sudo docker inspect --format='{{.State.Health.Status}}' postgres)
+      #         if [ "$health" = "healthy" ]; then
+      #           echo "Postgres is healthy!"
+      #           exit 0
+      #         fi
+      #         echo "Waiting for Postgres to be healthy..."
+      #         sleep 5
+      #       done
+      #       echo "Postgres did not become healthy in time." >&2
+      #       docker logs postgres
+      #       exit 1
 
       - name: Delete Old docker container
         run: sudo docker rm -f repo090924-container || true
